### PR TITLE
chore: Refactor lib structure to match `nimble` requiremenis

### PR DESCRIPTION
**Pull request by EmilIvanichkovv**
When I tried to add this project as `nimble` dependency the validation check failed. I noticed that the project structure does not have the required by nimble single directory hierarchy for source files, named 'dnsdisc'

### CODE REVIEW

**Comment by arnetheduck** [comment]
I think the better structure here would be to rename `discovery` to `src` and include a main `dnsdisc.nim`  file  in that `src` folder that reexports the principal modules - see https://github.com/nim-lang/nimble#project-structure - cc @jm-clius that probably has better insight in how distruptive this would be.

**Comment by jm-clius** [comment]
> I think the better structure here would be to rename discovery to src

Indeed. Spoke to @EmilIvanichkovv elsewhere and agreed to this approach. Impact will simply be a bit of import reconfiguration in nwaku, but that should be easy to address. Thanks for contributing, @EmilIvanichkovv !

**Comment by zah** [comment]
Most Status projects don't use the `src` folder structure. It hardly has any benefits and it makes consuming the project with the manual `--path:` approach more awkward. 

What we could do here is avoiding the double `dnsdisc/dnsdisc` nesting:

```bash
git mv dnsdisc temp
git mv temp/dnsdisc ./
rm -rf temp
```

And then create the usual `dnsdisc.nim` module at the root of the repo that imports and re-export all other modules. This is the standard structure we use in most packages.

**Comment by arnetheduck** [comment]
> Most Status projects don't use the src folder structure. 

I think we should start using it - the non-src structure is awkward in that when you add tests, documentation and other things that make up a quality library as the root folder becomes crowded - I'd prefer to see a standard setup that includes it. 

The tooling should take care of `--path` automatically - I don't see why this matters?

**Comment by zah** [comment]
But the root folder will be equally crowded with the `src` structure because the tests and the other items that you mentioned are not supposed to go under the `src` folder. The `src` folder is supposed to contain only the files that are used when consuming the library.

The supposed benefit of the `src` folder is that saves you the trouble of maintaining a `skipDirs` list in your nimble file.

**Comment by arnetheduck** [comment]
not quite, right? the point of `src` is to have a single location for the code that universally named across libraries, just like `tests` so you can access it conveniently and separately from everything else with _all_ standard unix tooling that works on a hierarchy basis making the setup a lot more interoperable in general... 

for a non-srcdir library you have `mylibrary.nim`  and a `mylibrary` folder whose name is different for every library (ie gets sorted differently, has a non-predictable name and so on) and things like `grep -r` cannot be constrained to the source code trivially.

Anyway, I don't feel too strongly about this - I find it convenient when libraries follow this structure because it makes them predictable in a way which is amenable and convenient for tooling and human pattern recognition alike and but you're right that most of our libraries don't do it - often because they were created ad-hoc by hand and dont have the aforementioned quality-of-library components that bring them to the point where the additional organisation is worth the 4-letter typing cost.

As far as this PR goes, we can do either - whether to include srcdir or not has no material impact on how the library is consumed (because in theory, if we had a working package manager, it would take care of this difference), so we can go with either in this PR and change to `src/` (or not) at a later point.

**Comment by EmilIvanichkovv** [comment]
Let's follow the more idiomatic for Status approach for now.

**Comment by jm-clius** [comment]
Thanks for your help! I think for the MAKE targets to work, the directory should also be updated in dnsdisc.nimble: https://github.com/status-im/nim-dnsdisc/blob/main/dnsdisc.nimble#L40

**Review by jm-clius — APPROVED** [review]
Thanks for this and for your patience!

**Pull request merged**
